language: node_js
node_js:
- node
cache:
  yarn: true
script:
- yarn test
deploy:
  provider: npm
  email: bulentv@gmail.com
  api_key:
    secure: FIdwCVjrP5ybw9M/r3Rx17nE1jTttRxXCLcdLU0TIn3dKFLQ7BaRh48Y0N9jAcxJswV5ArAAqrOOnvj4INMb7aFuaaNyju4JT4J5oAODloRI8rSOIOIbxusrC1RKiw3WRjn9eqIUnv2nShYvuF3Ib/P+YjrQgbAZvjRJZTkFPwBlDuBPFD9mTZ0W/YqhKeEzGnQ/OFYa9gbjF6olN5CtKgkZ4UJ4z2/FkYg79o/VGH3hj2TgoQc2peHv+Ih1rEK+isnpPNAVfwfkwXOBz2+W8F59FQGbgKeal0/25Ko/Upn//rUN+ZK/vm0r1dPYdPCIRJWwcqr+znT226RRNzapfzOKPWV4CIjrYAKkY4/yUuOW2+qd5m5wd3Ihpx1Dal8EOd6iD7lnvSC8w1iRqzBJJwv/1F0FZWe9fAxNOPqPAmNQ3p2xMGUBTHZVHGRjOG4zln7fydvYiYjE7m2xUbyMh3p/6H2HBJS9B49xItgRohKP7+zY8XzUzr/S9uV5f1mN6xdOA/77v9m0TZYHiuraB8okX/OwJodSAXowFFJrbjNMB+Ixdpia/h7Xex11lAuULuXGfrLX/owthe3kkPLT1gA0u4TiWYM1J9mUelHiwGtCRmMHiJOxgu04hhMJYc0LBavsRyhPlL/dggfUBGqc/V6JgdtIEdfe79hyai6GF/4=
  on:
    tags: true
    repo: bulentv/js_zklib
